version: '3.2'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peticket
      MYSQL_USER: peticket
      MYSQL_PASSWORD: peticket
    ports:
      - "3306:3306"

  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672


  pet-frontend:
    build: ./projPet/frontend/
    ports:
      - "3001:80"


  vet-frontend:
    build: ./projVet/frontend/
    ports:
      - "3002:80"


  func-frontend:
    build: ./projClinicFunc/frontend/
    ports:
      - "3003:80"


  display-frontend:
    build: ./projDS/frontend/
    ports:
      - "3004:80"


  # vet-service:
  #   depends_on:
  #     - db
  #     - rabbitmq
  #   build:
  #     context: ./projVet/vet
  #   restart: always
  #   ports:
  #     - "8081:8081"


  # pet-service:
  #   depends_on:
  #     - db
  #     - rabbitmq
  #   build:
  #     context: ./projPet/client
  #   restart: always
  #   ports:
  #     - "8080:8080"


  # func-service:
  #   depends_on:
  #     - db
  #     - rabbitmq
  #   build:
  #     context: ./projClinicFunc/func
  #   restart: always
  #   ports:
  #     - "8082:8082"
    

  # display-service:
  #   depends_on:
  #     - db
  #     - rabbitmq
  #   build:
  #     context: ./projDS/display
  #   restart: always
  #   ports:
  #     - "8888:8888"
   
