version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peticket
      MYSQL_USER: peticket
      MYSQL_PASSWORD: peticket
    ports:
      - "3306:3306"


