version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peticket
      MYSQL_USER: peticket
      MYSQL_PASSWORD: peticket
    ports:
      - "3306:3306"

  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672


  pet-frontend:
    build: ./projPet/frontend/
    ports:
      - "3001:80"
    networks:
      - peticket-net
      
  vet-frontend:
    build: ./projVet/frontend/
    ports:
      - "3002:80"
    networks:
      - peticket-net

  func-frontend:
    build: ./projClinicFunc/frontend/
    ports:
      - "3003:80"
    networks:
      - peticket-net

  display-frontend:
    build: ./projDS/frontend/
    ports:
      - "3004:80"
    networks:
      - peticket-net

  vet-service:
    depends_on:
      - db
      - rabbitmq
    build:
      context: ./projVet/vet
    restart: always
    ports:
      - "8081:8081"
    networks:
      - peticket-net

  pet-service:
    depends_on:
      - db
      - rabbitmq
    build:
      context: ./projPet/client
    restart: always
    ports:
      - "8080:8080"
    networks:
      - peticket-net

  func-service:
    depends_on:
      - db
      - rabbitmq
    build:
      context: ./projClinicFunc/func
    restart: always
    ports:
      - "8082:8082"
    networks:
      - peticket-net

  display-service:
    depends_on:
      - db
      - rabbitmq
    build:
      context: ./projDS/display
    restart: always
    ports:
      - "8888:8888"
    networks:
      - peticket-net      

networks:
    peticket-net:
        driver: bridge
