name: Continuous Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into the VM and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSW }}
        script: |
          cd ~/PeTicket
          git pull origin dev
          # Build and deploy using docker-compose
          docker-compose down
          docker-compose build
          docker-compose up -d
